workflows:
  my-workflow:
    name: My workflow name
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
      cancel_previous_builds: false
    scripts:
      - name: Build for iOS         # Name of the section
        script: flutter build ios   # The script(s) to be run in that section
    artifacts:
      - build/**/outputs/bundle/**/*.aab
    publishing:
      email:
        recipients:
          - doronkabaso10@gmail.com
      scripts:
        - echo 'Post-publish script'