name: flutter_firebase_auth
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 2.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.3.6
  firebase_core: ^1.0.2
  cloud_firestore: ^3.4.7
  provider: ^3.1.0
  pay: ^1.0.11
  fluttertoast: ^8.0.9
  google_sign_in: ^5.4.2

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/courts_top_view_sela.jpeg
    - assets/courts_top_view_sela2.jpeg
    - assets/girl_playing_sela.jpeg
    - assets/boy_playing_sela.jpeg
    - assets/boy_serving_sela.jpeg
    - assets/icon_sela.jpeg
    - assets/google_pay.json
    - assets/dudi_pay.json
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon_sela.jpeg"
